name: Beta
on:
  push:
    tags:
      - 12.0.beta
env:
  TAG: ${{ github.ref_name }}
jobs:
  vib-container:
    runs-on: ubuntu-latest
    name: Build Proxy Docker Image
    steps:
      - uses: actions/checkout@v2
        name: Checkout Java-lib Repository
        with:
          ref: dev-proxy2
          repository: wavefrontHQ/java-lib
      - name: Build Java-lib
        run: mvn --batch-mode install
      - uses: actions/checkout@v2
        name: Checkout Proxy Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: build application
        run: USER=${{ secrets.DOCKER_USER }} DOCKER_TAG=${{ env.TAG }} make build-jar cp-docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "./docker"
          platforms: linux/amd64,linux/arm/v7
          push: true
          build-args: "TEST=true"
          tags: "${{ secrets.DOCKER_OWNER }}/proxy-snapshot:${{ env.TAG }}"
