name: VIB
on: # rebuild any PRs and main branch changes
  pull_request:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    branches: ["**"]
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  vib-container:
    runs-on: ubuntu-latest
    name: Package Container
    steps:
      - uses: actions/checkout@v2
        name: Checkout Java-lib Repository
        with:
          ref: dev-proxy2
          repository: wavefrontHQ/java-lib
      - name: Build Java-lib
        run: mvn --batch-mode install
      - uses: actions/checkout@v2
        name: Checkout Proxy Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: build application
        run: USER=${{ secrets.DOCKER_USER }} DOCKER_TAG=${{ env.BRANCH_NAME }} MVN_ARGS=-DskipTests make build-jar docker-test
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/proxy-dev:${{ env.BRANCH_NAME }}
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Package Wavefront container
        with:
          pipeline: vib-container.json
        env:
          VIB_ENV_IMAGE_TAG: ${{ env.BRANCH_NAME }}
          VIB_ENV_DOCKER_USER: ${{ secrets.DOCKER_USER }}
  tests-chain-checking:
    runs-on: ubuntu-latest
    needs: vib-container
    steps:
      - id: run-params
        name: Dinamically generate runtime_params
        run: |
          echo "VIB_ENV_RUN_PARAMS=$(echo \
          "image:
            name: ${{ secrets.DOCKER_USER }}/proxy-dev
            tag: ${{ env.BRANCH_NAME }}
          wavefront:
            url: ${{ secrets.WF_MAIN_URL }}
            token: ${{ secrets.WF_MAIN_TOKEN }} " | base64 -w 0 )" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Verify Wavefront container
        with:
          pipeline: vib-chain-checking.json
        env:
          VIB_ENV_RUN_PARAMS: ${{ env.VIB_ENV_RUN_PARAMS }}
  tests-multi-tenant:
    runs-on: ubuntu-latest
    needs: vib-container
    steps:
      - id: run-params
        name: Dinamically generate runtime_params
        run: |
          echo "VIB_ENV_RUN_PARAMS=$(echo \
          "image:
            name: ${{ secrets.DOCKER_USER }}/proxy-dev
            tag: ${{ env.BRANCH_NAME }}
          wavefront:
            url: ${{ secrets.WF_MAIN_URL }}
            token: ${{ secrets.WF_MAIN_TOKEN }}
          wavefront_tenant:
            url: ${{ secrets.WF_TENANT_URL }}
            token: ${{ secrets.WF_TENANT_TOKEN }} " | base64 -w 0 )" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Verify Wavefront multi-tenant
        with:
          pipeline: vib-multi-tenant.json
        env:
          VIB_ENV_RUN_PARAMS: ${{ env.VIB_ENV_RUN_PARAMS }}
  tests-disk-buffer:
    runs-on: ubuntu-latest
    needs: vib-container
    steps:
      - id: run-params
        name: Dinamically generate runtime_params
        run: |
          echo "VIB_ENV_RUN_PARAMS=$(echo \
          "image:
            name: ${{ secrets.DOCKER_USER }}/proxy-dev
            tag: ${{ env.BRANCH_NAME }}
          wavefront:
            url: ${{ secrets.WF_MAIN_URL }}
            token: ${{ secrets.WF_MAIN_TOKEN }} " | base64 -w 0 )" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Verify Wavefront disk buffer
        with:
          pipeline: vib-disk-buffer.json
        env:
          VIB_ENV_RUN_PARAMS: ${{ env.VIB_ENV_RUN_PARAMS }} # tests-buffer-lock:
  #   runs-on: ubuntu-latest
  #   needs: vib-container
  #   steps:
  #     - uses: actions/checkout@v2
  #       name: Checkout Repository
  #       with:
  #         ref: ${{ github.event.pull_request.head.ref }}
  #         repository: ${{ github.event.pull_request.head.repo.full_name }}
  #     - uses: vmware-labs/vmware-image-builder-action@main
  #       name: Verify Wavefront container
  #       with:
  #         pipeline: vib-buffer-lock.json
  # tests-debian:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       name: Checkout Repository
  #       with:
  #         ref: ${{ github.event.pull_request.head.ref }}
  #         repository: ${{ github.event.pull_request.head.repo.full_name }}
  #     - uses: vmware-labs/vmware-image-builder-action@main
  #       name: Verify Wavefront container
  #       with:
  #         pipeline: vib-deb-package-debian.json
  # vib-maven:
  #   runs-on: ubuntu-latest
  #   name: make build-jar
  #   steps:
  #     - uses: actions/checkout@v2
  #       name: Checkout Java-lib Repository
  #       with:
  #         ref: dev-proxy2
  #         repository: wavefrontHQ/java-lib
  #     - name: Build Java-lib
  #       run: mvn --batch-mode install
  #     - uses: actions/checkout@v2
  #       name: Checkout Proxy Repository
  #       with:
  #         ref: ${{ github.event.pull_request.head.ref }}
  #         repository: ${{ github.event.pull_request.head.repo.full_name }}
  #     - name: build application
  #       run: make build-jar
  opentel-app-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v2
        name: Checkout Proxy Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: tests/opentel/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/opentel-app:${{ env.BRANCH_NAME }}
